---
title: "Simple document"
output: github_document
---

I'm an R Markdown document! 

# Section 1

```{r, echo = FLASE, message = FALSE}
library(tidyverse)
```

# import some data

I want to import 'FAS_ litters.cvs'.

```{r}
litters_df = read_csv("data/FAS_litters.csv")

#absolute path (only work in the path)
#read_csv("/Users/freya/Desktop/Data Science I P8105/In class code/data_wrangling_i/data/FAS_litters.csv")
```

Import the dataset. Now I want better names (changing the name)

```{r}
names(litters_df)

litters_df = janitor::clean_names(litters_df)
```

Look at the dataset

```{r}
litters_df

head(litters_df)
tail(litters_df)
```

One I use 

```{r, eval = FALSE}
view(litters_df)
```

Here's 'skimr':

```{r}
skimr::skim(litters_df)
```

## Arguments in 'read_csv'

```{r, eval = FALSE}
litters_df = read_csv("data/FAS_litters.csv",
                      skip = 5,
                      col_names = FALSE,
                      na = "Low8")
```

# Parsing columns
```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv",
  col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  )
)
tail(litters_data)
```

